// <auto-generated />
using System;
using DataAcquisition.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAcquisition.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210213165742_initialDbCreation")]
    partial class initialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.ApplicationInfo", b =>
                {
                    b.Property<string>("ApplicationName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstInstallDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationName");

                    b.ToTable("ApplicationInfo");

                    b.HasData(
                        new
                        {
                            ApplicationName = "DataAcquisition",
                            FirstInstallDate = new DateTime(2021, 2, 13, 16, 57, 42, 158, DateTimeKind.Local).AddTicks(8587),
                            LastUpdateDate = new DateTime(2021, 2, 13, 16, 57, 42, 160, DateTimeKind.Local).AddTicks(8951),
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Experiment", b =>
                {
                    b.Property<Guid>("ExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperimentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperimentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExperimentId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Facility", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Workstation", b =>
                {
                    b.Property<Guid>("WorkstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkstationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkstationId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("DeviceExperiment", b =>
                {
                    b.Property<Guid>("DevicesDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperimentsExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DevicesDeviceId", "ExperimentsExperimentId");

                    b.HasIndex("ExperimentsExperimentId");

                    b.ToTable("DeviceExperiment");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Device", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.Workstation", "Workstation")
                        .WithMany("Devices")
                        .HasForeignKey("WorkstationId");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Experiment", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.User", "User")
                        .WithMany("Experiments")
                        .HasForeignKey("UserId");

                    b.HasOne("DataAcquisition.Core.Models.Entities.Workstation", "WorkStation")
                        .WithMany("Experiments")
                        .HasForeignKey("WorkstationId");

                    b.Navigation("User");

                    b.Navigation("WorkStation");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Facility", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.Company", "Company")
                        .WithMany("Facilities")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.User", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Workstation", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.Facility", "Facility")
                        .WithMany("WorkStations")
                        .HasForeignKey("FacilityId");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("DeviceExperiment", b =>
                {
                    b.HasOne("DataAcquisition.Core.Models.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcquisition.Core.Models.Entities.Experiment", null)
                        .WithMany()
                        .HasForeignKey("ExperimentsExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Company", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Facility", b =>
                {
                    b.Navigation("WorkStations");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.User", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("DataAcquisition.Core.Models.Entities.Workstation", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
