@startuml "Data Acquisition Project Structure Diagram"
!include <c4/C4_Container.puml>

LAYOUT_LEFT_RIGHT()
HIDE_STEREOTYPE()

Person(user, User, "A tech person")

Container_Boundary(db, "Database Structure") {
    System(company, "Company", " ")
    System(facility, "Facility", " ")
    System(ws, "Workstation", " ")
    System(device, "Device", " ")
    System(exp, "Experiment", " ")
}


Rel(user, company, "has one")
Rel(company, facility, "has many")
Rel(facility, ws, "has many")
Rel(ws, exp, "has many")
Rel(ws, device, "has many")
Rel(user, exp, "has many")

@enduml
